# Generated by Django 3.2 on 2022-02-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ModelVegetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vegetable_label', models.IntegerField()),
                ('vegetable_name', models.CharField(max_length=50)),
                ('vegetable_price_firsthalf', models.CharField(max_length=100)),
                ('vegetable_price_secondhalf', models.CharField(max_length=100)),
                ('vegetable_price_info', models.CharField(max_length=100)),
            ],
        ),
    ]
