# Generated by Django 3.2 on 2022-02-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvegetable',
            name='vegetable_price_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
